version: 0.0
os: linux
files:
   - source: /
     destination: /var/grassroot-learning
permissions:
   - object: /var/grassroot-learning
     pattern: "**"
     owner: root 
     group: root 
     mode: 755
hooks:
   BeforeInstall:
    - location: scripts/stoplearning.sh
    - location: scripts/archivelearning.sh
      runas: root
   AfterInstall:
    - location: scripts/compilelearning.sh
      runas: root
   ApplicationStart:
    - location: scripts/startlearning.sh
      runas: root