version: 2

step-library:
  - &fetch-aws-cli
      run:
        name:
        command: |
          sudo apt-get update && sudo apt-get install python && sudo apt-get install python-pip && sudo apt-get install python-dev
          pip install awscli --upgrade --user
          pip install awsebcli --upgrade --user


jobs:
  dependencies:
    docker:
      - images: circleci/python:3.6.1


  build:
    docker:
      - image: circleci/python:3.6.1
      services:
      - docker

  deploy-production:
    command: |
        # Build image and push to Docker Hub
        - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
        - bash ./buildDocker.sh
        #- docker pull grassrootdocker/terafirma:alpha

        # deploy files to beanstalk
        - bash ./eb/setup-eb.sh
        - eb init gr-learning -p "64bit Amazon Linux 2017.03 v2.7.1 running Docker 17.03.1-ce" -r eu-west-1 -k nlu-prep-key.pem
        - eb deploy


workflows:
  version: 2
    jobs:
    - dependencies
    - build:
    - deploy-production:
        requires:
          - build
        filters:
          branches:
            only: circle2-working