version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
        auth:
            username: $DOCKER_USER
            password: $DOCKER_PASS
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker build -t terafirma .
          docker tag terafirma grassrootdocker/terafirma:skywalker
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push grassrootdocker/terafirma:skywalker

  deploy:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run: 
          name: deploy
          command: |
            sudo -H pip install awscli
            sudo -H pip install awsebcli
            aws elasticbeanstalk update-environment --environment-name learning-staging --region eu-west-1
            
  test:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run: 
          command: |
            sudo -H pip install awscli
            sudo -H pip install awsebcli

workflows:
  version: 2
  build_and_test:
    jobs:
      # - build
      # - test:
      #     requires:
      #       - build
      - deploy