comex = [{'entities': [], 'intent': 'affirm', 'text': "that's right"},
 {'entities': [], 'intent': 'affirm', 'text': 'ok'},
 {'entities': [], 'intent': 'affirm', 'text': 'great'},
 {'entities': [], 'intent': 'affirm', 'text': 'right, thank you'},
 {'entities': [], 'intent': 'affirm', 'text': 'correct'},
 {'entities': [], 'intent': 'affirm', 'text': 'great choice'},
 {'entities': [], 'intent': 'affirm', 'text': 'sounds really good'},
 {'entities': [],
  'intent': 'set_meeting',
  'text': "I would (I'd) like to request a meeting"},
 {'entities': [], 'intent': 'set_meeting', 'text': 'Record a meeting'},
 {'entities': [{'end': 29, 'entity': 'location', 'start': 25, 'value': 'Paki'},
   {'end': 49, 'entity': 'subject', 'start': 34, 'value': 'housing permits'}],
  'intent': 'set_meeting',
  'text': 'We would like to meet at Paki for housing permits'},
 {'entities': [], 'intent': 'set_meeting', 'text': 'set up a meeting'},
 {'entities': [], 'intent': 'set_meeting', 'text': 'set meeting'},
 {'entities': [],
  'intent': 'set_meeting',
  'text': "I'd like to set a meeting"},
 {'entities': [{'end': 29,
    'entity': 'subject',
    'start': 22,
    'value': 'housing'},
   {'end': 42, 'entity': 'date_time', 'start': 39, 'value': '2pm'}],
  'intent': 'set_meeting',
  'text': 'Start a meeting about housing today at 6pm'},
 {'entities': [{'end': 34,
    'entity': 'organization',
    'start': 22,
    'value': 'Khotso House'},
   {'end': 42, 'entity': 'date_time', 'start': 39, 'value': '2pm'}],
  'intent': 'set_meeting',
  'text': 'Arrange a meeting for Khotso House for 2pm'},
 {'entities': [{'end': 35,
    'entity': 'subject',
    'start': 25,
    'value': 'sanitation'},
   {'end': 20, 'entity': 'date_time', 'start': 17, 'value': '5pm'}],
  'intent': 'set_meeting',
  'text': 'Set a meeting at 5pm for Sanitation'},
 {'entities': [{'end': 27,
    'entity': 'organization',
    'start': 0,
    'value': 'Greater Kliptown Leadership'},
   {'end': 68,
    'entity': 'date_time',
    'start': 47,
    'value': 'this Saturday 10am'}],
  'intent': 'set_meeting',
  'text': 'Greater Kliptown Leadership would like to meet this Saturday at 10am'},
 {'entities': [{'end': 33,
    'entity': 'organization',
    'start': 29,
    'value': 'SOPA'},
   {'end': 46, 'entity': 'date_time', 'start': 34, 'value': 'this Tuesday'}],
  'intent': 'set_meeting',
  'text': 'Generate meeting request for SOPA this Tuesday'},
 {'entities': [{'end': 42,
    'entity': 'date_time',
    'start': 30,
    'value': 'today at 3pm'},
   {'end': 53, 'entity': 'location', 'start': 46, 'value': 'Jozihub'}],
  'intent': 'set_meeting',
  'text': 'I would like to set a meeting today at 3pm at Jozihub'},
 {'entities': [{'end': 39,
    'entity': 'date_time',
    'start': 21,
    'value': 'next week Saturday'},
   {'end': 52, 'entity': 'location', 'start': 43, 'value': 'Starbucks'}],
  'intent': 'set_meeting',
  'text': 'Set up a meeting for next week Saturday at Starbucks'},
 {'entities': [{'end': 50,
    'entity': 'date_time',
    'start': 34,
    'value': 'tomorrow at 12pm'},
   {'end': 60, 'entity': 'location', 'start': 51, 'value': 'Enkomponi'}],
  'intent': 'set_meeting',
  'text': 'I would like to set a meeting for tomorrow at 12pm Enkomponi'},
 {'entities': [], 'intent': 'negation', 'text': 'No this is not what I want'},
 {'entities': [], 'intent': 'negation', 'text': 'No'},
 {'entities': [], 'intent': 'negation', 'text': 'negative'},
 {'entities': [], 'intent': 'affirm', 'text': 'yes'},
 {'entities': [], 'intent': 'affirm', 'text': 'yep'},
 {'entities': [], 'intent': 'affirm', 'text': 'yeah'},
 {'entities': [], 'intent': 'affirm', 'text': 'indeed'},
 {'entities': [{'end': 16,
    'entity': 'location',
    'start': 9,
    'value': 'Jozihub'},
   {'end': 36, 'entity': 'date_time', 'start': 18, 'value': '2pm today'},
   {'end': 54, 'entity': 'subject', 'start': 38, 'value': 'feedback_session'}],
  'intent': 'set_meeting',
  'text': "Meeting, Jozihub, 2pm/o'clock, today, feedback session"},
 {'entities': [{'end': 15,
    'entity': 'location',
    'start': 8,
    'value': 'Jozihub'},
   {'end': 60, 'entity': 'date_time', 'start': 51, 'value': '2pm today'},
   {'end': 42, 'entity': 'subject', 'start': 26, 'value': 'feedback_session'}],
  'intent': 'set_meeting',
  'text': 'Meet at Jozihub about the Feedback session week at 2pm today'},
 {'entities': [{'end': 67,
    'entity': 'location',
    'start': 60,
    'value': 'Jozihub'},
   {'end': 56, 'entity': 'subject', 'start': 40, 'value': 'feedback_session'},
   {'end': 29, 'entity': 'date_time', 'start': 9, 'value': '2pm today'}],
  'intent': 'set_meeting',
  'text': "Meeting, today at 2pm/o'clock about the Feedback session at Jozihub"},
 {'entities': [{'end': 42,
    'entity': 'location',
    'start': 35,
    'value': 'Jozihub'},
   {'end': 31, 'entity': 'subject', 'start': 15, 'value': 'feedback_session'},
   {'end': 70, 'entity': 'date_time', 'start': 43, 'value': '2pm today'}],
  'intent': 'set_meeting',
  'text': 'Meet about the Feedback session at Jozihub today at 2 in the afternoon'},
 {'entities': [{'end': 41,
    'entity': 'date_time',
    'start': 20,
    'value': '5pm tomorrow'},
   {'end': 18, 'entity': 'location', 'start': 9, 'value': 'Enkomponi'},
   {'end': 57, 'entity': 'subject', 'start': 43, 'value': 'protest_action'}],
  'intent': 'set_meeting',
  'text': "Meeting, Enkomponi, 5pm/o'clock, tomorrow, protest action"},
 {'entities': [{'end': 67,
    'entity': 'date_time',
    'start': 46,
    'value': '5pm tomorrow'},
   {'end': 20, 'entity': 'location', 'start': 11, 'value': 'Enkomponi'},
   {'end': 42, 'entity': 'subject', 'start': 28, 'value': 'protest_action'}],
  'intent': 'set_meeting',
  'text': "Meeting at Enkomponi, about protest action at 5pm/o'clock, tomorrow"},
 {'entities': [{'end': 38,
    'entity': 'location',
    'start': 29,
    'value': 'Enkomponi'},
   {'end': 25, 'entity': 'subject', 'start': 11, 'value': 'protest_action'},
   {'end': 67, 'entity': 'date_time', 'start': 39, 'value': '5pm tomorrow'}],
  'intent': 'set_meeting',
  'text': 'Meet about protest action at Enkomponi tomorrow at 5 in the evening'},
 {'entities': [{'end': 48,
    'entity': 'location',
    'start': 39,
    'value': 'Enkomponi'},
   {'end': 14, 'entity': 'subject', 'start': 0, 'value': 'protest_action'},
   {'end': 37, 'entity': 'date_time', 'start': 16, 'value': '5pm tomorrow'}],
  'intent': 'set_meeting',
  'text': "Protest action, tomorrow, 5pm/o'clock, Enkomponi, meeting"},
 {'entities': [{'end': 35,
    'entity': 'date_time',
    'start': 14,
    'value': '9am Saturday'},
   {'end': 12, 'entity': 'location', 'start': 9, 'value': 'KYP'},
   {'end': 53, 'entity': 'subject', 'start': 37, 'value': 'discussion_group'}],
  'intent': 'set_meeting',
  'text': "Meeting, KYP, 9am/o'clock, Saturday, Discussion Group"},
 {'entities': [{'end': 68,
    'entity': 'date_time',
    'start': 42,
    'value': '9am this Saturday'},
   {'end': 14, 'entity': 'location', 'start': 11, 'value': 'KYP'},
   {'end': 38, 'entity': 'subject', 'start': 22, 'value': 'discussion_group'}],
  'intent': 'set_meeting',
  'text': "Meeting at KYP, about Discussion Group at 9am/o'clock, this Saturday"},
 {'entities': [{'end': 16,
    'entity': 'subject',
    'start': 0,
    'value': 'feedback_session'},
   {'end': 63, 'entity': 'location', 'start': 60, 'value': 'KYP'},
   {'end': 58,
    'entity': 'date_time',
    'start': 18,
    'value': '9am last Saturday of the month'}],
  'intent': 'set_meeting',
  'text': "Feedback session, last Saturday of this month, 9am/o'clock, KYP, meeting"},
 {'entities': [{'end': 29,
    'entity': 'location',
    'start': 20,
    'value': 'Enkomponi'}],
  'intent': 'set_meeting',
  'text': 'I want a meeting at Enkomponi'},
 {'entities': [{'end': 32,
    'entity': 'subject',
    'start': 21,
    'value': 'electricity'}],
  'intent': 'set_meeting',
  'text': 'Urgent meeting about electricity'},
 {'entities': [{'end': 35,
    'entity': 'location',
    'start': 21,
    'value': 'Sports Complex'},
   {'end': 3, 'entity': 'organization', 'start': 0, 'value': 'TCC'}],
  'intent': 'set_meeting',
  'text': 'TCC has a meeting at Sports Complex'},
 {'entities': [{'end': 16, 'entity': 'location', 'start': 13, 'value': 'KYP'}],
  'intent': 'set_meeting',
  'text': 'Lets meet at KYP'},
 {'entities': [{'end': 36,
    'entity': 'date_time',
    'start': 23,
    'value': '2pm Monday'}],
  'intent': 'set_meeting',
  'text': 'Schedule a meeting for 2pm on Monday'},
 {'entities': [{'end': 40,
    'entity': 'location',
    'start': 20,
    'value': 'Walter Sisulu Square'}],
  'intent': 'set_meeting',
  'text': 'Create a meeting at Walter Sisulu Square'},
 {'entities': [{'end': 43,
    'entity': 'location',
    'start': 23,
    'value': 'Freedom Park Primary'}],
  'intent': 'set_meeting',
  'text': 'Lets have a meeting at Freedom Park Primary'},
 {'entities': [{'end': 32,
    'entity': 'date_time',
    'start': 25,
    'value': 'tonight'}],
  'intent': 'set_meeting',
  'text': 'Do a meeting request for tonight'},
 {'entities': [{'end': 7,
    'entity': 'location',
    'start': 0,
    'value': 'Jozihub'}],
  'intent': 'None',
  'text': 'Jozihub'},
 {'entities': [{'end': 9,
    'entity': 'location',
    'start': 0,
    'value': 'Enkomponi'}],
  'intent': 'None',
  'text': 'Enkomponi'},
 {'entities': [{'end': 36,
    'entity': 'date_time',
    'start': 24,
    'value': '13 July'}],
  'intent': 'set_meeting',
  'text': 'I want a meeting on the 13th of July'},
 {'entities': [{'end': 37,
    'entity': 'location',
    'start': 30,
    'value': 'Milpark'}],
  'intent': 'set_meeting',
  'text': 'Set a meeting up for today at Milpark'},
 {'entities': [{'end': 47,
    'entity': 'date_time',
    'start': 30,
    'value': 'this evening at 7'}],
  'intent': 'set_meeting',
  'text': 'Execute a meeting request for this evening at 7'},
 {'entities': [{'end': 50,
    'entity': 'organization',
    'start': 26,
    'value': 'Mnandini Community Group'}],
  'intent': 'set_meeting',
  'text': 'Send a meeting request to Mnandini Community Group'},
 {'entities': [{'end': 48,
    'entity': 'date_time',
    'start': 36,
    'value': 'today at 5pm'}],
  'intent': 'set_meeting',
  'text': 'I would like to order a meeting for today at 5pm'},
 {'entities': [{'end': 38,
    'entity': 'date_time',
    'start': 19,
    'value': 'next Tuesday at 5pm'}],
  'intent': 'set_meeting',
  'text': 'Plan a meeting for next Tuesday at 5pm'},
 {'entities': [{'end': 3, 'entity': 'date_time', 'start': 0, 'value': '2pm'}],
  'intent': 'None',
  'text': '2pm'},
 {'entities': [{'end': 55,
    'entity': 'organization',
    'start': 41,
    'value': 'Abahlali Forum'}],
  'intent': 'set_meeting',
  'text': 'Carry out a meeting request on behalf of Abahlali Forum'},
 {'entities': [{'end': 8,
    'entity': 'date_time',
    'start': 0,
    'value': 'tomorrow'}],
  'intent': 'None',
  'text': 'tomorrow'},
 {'entities': [{'end': 5,
    'entity': 'date_time',
    'start': 0,
    'value': 'today'}],
  'intent': 'None',
  'text': 'today'},
 {'entities': [{'end': 13,
    'entity': 'date_time',
    'start': 0,
    'value': 'next Saturday'}],
  'intent': 'None',
  'text': 'next Saturday'},
 {'entities': [{'end': 14,
    'entity': 'organization',
    'start': 0,
    'value': 'Abahlali Forum'}],
  'intent': 'None',
  'text': 'Abahlali Forum'},
 {'entities': [{'end': 16,
    'entity': 'subject',
    'start': 0,
    'value': 'discussion_group'}],
  'intent': 'None',
  'text': 'Discussion group'},
 {'entities': [{'end': 14,
    'entity': 'subject',
    'start': 0,
    'value': 'protest_action'}],
  'intent': 'None',
  'text': 'protest action'},
 {'entities': [{'end': 16,
    'entity': 'subject',
    'start': 0,
    'value': 'feedback_session'}],
  'intent': 'None',
  'text': 'Feedback session'},
 {'entities': [{'end': 12,
    'entity': 'date_time',
    'start': 0,
    'value': 'today at 3pm'}],
  'intent': 'None',
  'text': 'today at 3pm'},
 {'entities': [{'end': 18,
    'entity': 'date_time',
    'start': 0,
    'value': 'next week Saturday'}],
  'intent': 'None',
  'text': 'next week Saturday'},
 {'entities': [{'end': 26,
    'entity': 'date_time',
    'start': 0,
    'value': 'last Saturday of the month'}],
  'intent': 'None',
  'text': 'last Saturday of the month'},
 {'entities': [{'end': 9,
    'entity': 'location',
    'start': 0,
    'value': 'Starbucks'}],
  'intent': 'None',
  'text': 'Starbucks'},
 {'entities': [{'end': 18,
    'entity': 'location',
    'start': 11,
    'value': 'Jozihub'}],
  'intent': 'negation',
  'text': 'no I meant Jozihub'},
 {'entities': [{'end': 13,
    'entity': 'location',
    'start': 4,
    'value': 'Enkomponi'}],
  'intent': 'negation',
  'text': 'no, Enkomponi'},
 {'entities': [{'end': 45, 'entity': 'location', 'start': 42, 'value': 'KYP'}],
  'intent': 'negation',
  'text': "no I think I'd rather have the meeting at KYP"},
 {'entities': [{'end': 25,
    'entity': 'organization',
    'start': 11,
    'value': 'Abahlali Forum'}],
  'intent': 'negation',
  'text': 'No I meant Abahlali Forum'},
 {'entities': [{'end': 17,
    'entity': 'organization',
    'start': 4,
    'value': 'Hackers Union'}],
  'intent': 'negation',
  'text': 'No, Hackers Union'},
 {'entities': [{'end': 42,
    'entity': 'organization',
    'start': 29,
    'value': 'Hackers Union'}],
  'intent': 'negation',
  'text': "No I'd like to meet with the Hackers Union"},
 {'entities': [{'end': 25,
    'entity': 'subject',
    'start': 11,
    'value': 'protest_action'}],
  'intent': 'negation',
  'text': 'No I meant protest action'},
 {'entities': [{'end': 24,
    'entity': 'date_time',
    'start': 11,
    'value': 'this Saturday'}],
  'intent': 'negation',
  'text': 'No I meant this Saturday'},
 {'entities': [{'end': 42,
    'entity': 'date_time',
    'start': 15,
    'value': 'last Saturday of this month'}],
  'intent': 'negation',
  'text': 'no I meant the last Saturday of this month'},
 {'entities': [{'end': 8,
    'entity': 'date_time',
    'start': 3,
    'value': 'today'}],
  'intent': 'negation',
  'text': 'no today'}]