examples = ["Set a meeting at Jozihub", "I'd like to have a meeting at Jozihub today, 3pm about the Feedback session",
"Meeting , Jozihub, 2pm/o'clock, today, Feedback session",
"Meet at Jozihub about Feedback session week at 2pm today",
"Meeting, today at 2pm/o'clock about the Feedback session at Jozihub",
"Meet at JoziHub today for Feedback session at 2pm/o'clock",
"Meet about the Feedback session at JoziHub today at 2 in the afternoon",
"Feedback session, today, 2pm/o'clock, JoziHub, meeting",
"Meeting, Enkomponi, 5pm/o'clock, tomorrow, protest action",
"Meeting at Enkomponi, about protest action at 5pm/o'clock, tomorrow",
"Meeting, tomorrow at 5pm/o’clock about protest action at Enkomponi",
"Meet at Enkomponi tomorrow for protest action at 5 pm/o'clock",
"Meet about protest action at Enkomponi tomorrow at 5 in the evening",
"Protest action, tomorrow, 5pm/o'clock, Enkomponi, meeting",
"Meeting, KYP, 9am/o'clock, Saturday, Discussion Group",
"Meeting at KYP, about Discussion Group at 9am/o'clock, this Saturday",
"Meeting, next Saturday at 9am/o'clock about the Discussion Group at KYP",
"Meet at KYP, Saturday after next for Discussion Group at 9 in the morning",
"Feedback session, last Saturday of this month, 9am/o'clock, KYP, meeting",
"I want a meeting at Enkomponi",
"Call a meeting for 2pm an Jozihub",
"I would (I’d) like to request a meeting",
"Urgent meeting about Electricity",
"Record a meeting",
"TCC has a meeting at Sports Complex",
"We would like to meet at Paki for housing permits",
"Let’s meet at KYP",
"Schedule a meeting for 2pm on Monday",
"Organize a meeting at The Containers",
"Create a meeting at Walter Sisulu Square",
"Let’s have a meeting at Freedom Park Primary",
"Do a meeting request for tonight",
"I want a meeting on the  13th of July",
"Strat a meeting about housing today at 6pm",
"Start meeting request for Kliptown community",
"Arrange a meeting for Khotso House for 2pm",
"Set up a meeting at 5pm for Sanitation",
"Set a meeting up for today at Milpark",
"Execute a meeting request for this evening at 7",
"Send meeting request to Mnandini Community Group",
"I would like to order a meeting for today at 5pm",
"Greater Kliptown Leadership would like to meet this Saturday at 10am",
"Plan a meeting for next Tuesday a t 5pm",
"Generate meeting request for SOPA this Tuesday",
"Carry out a meeting request on behalf of Abahlali Forum"]